require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/batches", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Batch. As you add validations to Batch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Batch.create! valid_attributes
      get batches_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      batch = Batch.create! valid_attributes
      get batch_url(batch)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_batch_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      batch = Batch.create! valid_attributes
      get edit_batch_url(batch)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Batch" do
        expect {
          post batches_url, params: { batch: valid_attributes }
        }.to change(Batch, :count).by(1)
      end

      it "redirects to the created batch" do
        post batches_url, params: { batch: valid_attributes }
        expect(response).to redirect_to(batch_url(Batch.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Batch" do
        expect {
          post batches_url, params: { batch: invalid_attributes }
        }.to change(Batch, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post batches_url, params: { batch: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested batch" do
        batch = Batch.create! valid_attributes
        patch batch_url(batch), params: { batch: new_attributes }
        batch.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the batch" do
        batch = Batch.create! valid_attributes
        patch batch_url(batch), params: { batch: new_attributes }
        batch.reload
        expect(response).to redirect_to(batch_url(batch))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        batch = Batch.create! valid_attributes
        patch batch_url(batch), params: { batch: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested batch" do
      batch = Batch.create! valid_attributes
      expect {
        delete batch_url(batch)
      }.to change(Batch, :count).by(-1)
    end

    it "redirects to the batches list" do
      batch = Batch.create! valid_attributes
      delete batch_url(batch)
      expect(response).to redirect_to(batches_url)
    end
  end
end
